spring.application.name=Service

server.servlet.context-path=/rest

spring.main.lazy-initialization=true

logging.level.org.springframework=info
logging.level.com.pioneers.service=trace

spring.messages.basename=validations_en
