spring.application.name=university-task
server.servlet.context-path=/rest

logging.level.root=info

logging.level.org.springframework=info
logging.level.com.example.universitytask=trace

spell.checker.ownerName=Tech Pioneers Hub
spell.checker.version=V1.1

# DB Config
db.username=biiiigDb
db.password=TPH!%s2#
db.database=test
db.url=jdbc:mysql://192.168.0.100:3306/test
db.connection-pool-properties.max-open-connections=200
db.connection-pool-properties.max-idle-connections=70
db.connection-pool-properties.timeout=1000

db.connection.flow=false

db.postgres.enabled=true
db.liquibase.enabled=false

